-- FinoLens v2 — PostgreSQL Schema
-- Run: psql -U finolens -d finolens_db -f schema.sql

-- ─────────────────────────────────────────────
-- Extensions
-- ─────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ─────────────────────────────────────────────
-- Stocks master list (NSE)
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stocks (
  id               SERIAL PRIMARY KEY,
  symbol           VARCHAR(20)  UNIQUE NOT NULL,
  instrument_token BIGINT       UNIQUE,
  name             VARCHAR(200),
  exchange         VARCHAR(10)  NOT NULL DEFAULT 'NSE',
  sector           VARCHAR(100),
  is_active        BOOLEAN      NOT NULL DEFAULT true,
  created_at       TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_stocks_symbol ON stocks(symbol);
CREATE INDEX IF NOT EXISTS idx_stocks_active ON stocks(is_active);

-- ─────────────────────────────────────────────
-- User watchlist
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS watchlist (
  id         SERIAL    PRIMARY KEY,
  stock_id   INT       NOT NULL REFERENCES stocks(id) ON DELETE CASCADE,
  added_at   TIMESTAMP NOT NULL DEFAULT NOW(),
  notes      TEXT,
  UNIQUE(stock_id)
);

CREATE INDEX IF NOT EXISTS idx_watchlist_stock ON watchlist(stock_id);

-- ─────────────────────────────────────────────
-- Signals generated by engine
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS signals (
  id                  SERIAL          PRIMARY KEY,
  stock_id            INT             NOT NULL REFERENCES stocks(id) ON DELETE CASCADE,
  signal_type         VARCHAR(10)     NOT NULL CHECK (signal_type IN ('BUY','SELL','NEUTRAL')),
  confidence          DECIMAL(5,2)    NOT NULL CHECK (confidence >= 0 AND confidence <= 100),
  entry_price         DECIMAL(10,2)   NOT NULL,
  suggested_stop_loss DECIMAL(10,2),
  suggested_target    DECIMAL(10,2),
  rsi_value           DECIMAL(6,2),
  macd_value          DECIMAL(10,4),
  ema_20              DECIMAL(10,2),
  ema_50              DECIMAL(10,2),
  adx_value           DECIMAL(6,2),
  bb_position         VARCHAR(20)     CHECK (bb_position IN ('UPPER','MIDDLE','LOWER')),
  supertrend_signal   VARCHAR(10)     CHECK (supertrend_signal IN ('UP','DOWN')),
  reasoning           TEXT,
  generated_at        TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_signals_stock    ON signals(stock_id);
CREATE INDEX IF NOT EXISTS idx_signals_type     ON signals(signal_type);
CREATE INDEX IF NOT EXISTS idx_signals_generated ON signals(generated_at DESC);

-- ─────────────────────────────────────────────
-- Outcome tracking — measures actual vs predicted
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS signal_outcomes (
  id               SERIAL        PRIMARY KEY,
  signal_id        INT           NOT NULL UNIQUE REFERENCES signals(id) ON DELETE CASCADE,
  price_after_1d   DECIMAL(10,2),
  price_after_3d   DECIMAL(10,2),
  price_after_5d   DECIMAL(10,2),
  price_after_10d  DECIMAL(10,2),
  max_profit_pct   DECIMAL(6,2),
  max_loss_pct     DECIMAL(6,2),
  outcome          VARCHAR(20)   CHECK (outcome IN ('WIN','LOSS','BREAKEVEN','OPEN')),
  evaluated_at     TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_outcomes_signal  ON signal_outcomes(signal_id);
CREATE INDEX IF NOT EXISTS idx_outcomes_outcome ON signal_outcomes(outcome);

-- ─────────────────────────────────────────────
-- Paper trades
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS paper_trades (
  id           SERIAL        PRIMARY KEY,
  signal_id    INT           REFERENCES signals(id) ON DELETE SET NULL,
  stock_id     INT           NOT NULL REFERENCES stocks(id) ON DELETE CASCADE,
  trade_type   VARCHAR(10)   NOT NULL CHECK (trade_type IN ('BUY','SELL')),
  quantity     INT           NOT NULL CHECK (quantity > 0),
  entry_price  DECIMAL(10,2) NOT NULL,
  entry_time   TIMESTAMP     NOT NULL DEFAULT NOW(),
  exit_price   DECIMAL(10,2),
  exit_time    TIMESTAMP,
  exit_reason  VARCHAR(50)   CHECK (exit_reason IN ('TARGET_HIT','STOP_LOSS','MANUAL','TIMEOUT')),
  pnl          DECIMAL(10,2),
  pnl_pct      DECIMAL(6,2),
  status       VARCHAR(20)   NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','CLOSED'))
);

CREATE INDEX IF NOT EXISTS idx_trades_stock  ON paper_trades(stock_id);
CREATE INDEX IF NOT EXISTS idx_trades_status ON paper_trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_entry  ON paper_trades(entry_time DESC);

-- ─────────────────────────────────────────────
-- Kite session storage
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS kite_sessions (
  id           SERIAL      PRIMARY KEY,
  user_id      VARCHAR(50) UNIQUE NOT NULL,
  access_token TEXT        NOT NULL,
  public_token TEXT,
  expires_at   TIMESTAMP   NOT NULL,
  created_at   TIMESTAMP   NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────
-- Seed: common NSE Nifty 50 stocks
-- ─────────────────────────────────────────────
INSERT INTO stocks (symbol, name, sector) VALUES
  ('RELIANCE',    'Reliance Industries Ltd',        'Energy'),
  ('TCS',         'Tata Consultancy Services Ltd',  'Technology'),
  ('HDFCBANK',    'HDFC Bank Ltd',                  'Banking'),
  ('INFY',        'Infosys Ltd',                    'Technology'),
  ('ICICIBANK',   'ICICI Bank Ltd',                 'Banking'),
  ('HINDUNILVR',  'Hindustan Unilever Ltd',          'FMCG'),
  ('ITC',         'ITC Ltd',                        'FMCG'),
  ('SBIN',        'State Bank of India',             'Banking'),
  ('BAJFINANCE',  'Bajaj Finance Ltd',               'Finance'),
  ('BHARTIARTL',  'Bharti Airtel Ltd',               'Telecom'),
  ('KOTAKBANK',   'Kotak Mahindra Bank Ltd',         'Banking'),
  ('LT',          'Larsen & Toubro Ltd',             'Infrastructure'),
  ('HCLTECH',     'HCL Technologies Ltd',            'Technology'),
  ('ASIANPAINT',  'Asian Paints Ltd',                'Consumer'),
  ('AXISBANK',    'Axis Bank Ltd',                   'Banking'),
  ('MARUTI',      'Maruti Suzuki India Ltd',         'Automobile'),
  ('SUNPHARMA',   'Sun Pharmaceutical Industries',   'Pharma'),
  ('TITAN',       'Titan Company Ltd',               'Consumer'),
  ('WIPRO',       'Wipro Ltd',                       'Technology'),
  ('ULTRACEMCO',  'UltraTech Cement Ltd',            'Materials')
ON CONFLICT (symbol) DO NOTHING;
